---

- name: Install brightnessd script
  copy:
    dest: '{{ inventory_dir }}/root/usr/sbin/brightnessd'
    src: brightnessd
    mode: 0755

- name: Install required packages
  command: 'chroot {{ inventory_dir }}/root apt-get install --assume-yes --allow-unauthenticated python3 python3-smbus'

- name: Install brightnessd service
  copy:
    dest: '{{ inventory_dir}}/root/etc/systemd/system/brightnessd.service'
    src: brightnessd.service

- name: Enable brightnessd service
  command: 'chroot {{ inventory_dir }}/root systemctl status brightnessd'

- name: Load module {{ item }} on boot
  lineinfile:
    path: '{{ inventory_dir}}/root/etc/modules'
    line: '{{ item }}'
  with_items:
    - i2c-dev
    - openframe_bl
