---
- name: Set kernel audio module flags
  # https://www.jogglerwiki.com/forum/viewtopic.php?p=19156#p19156
  copy:
    dest: '{{ inventory_dir }}/root/etc/modprobe.d/joggler-audio.conf'
    content: 'options snd-hda-intel position_fix=1 bdl_pos_adj=64 model=ref'

- name: Install alsa-utils
  command: 'chroot {{ inventory_dir }}/root apt-get install --assume-yes --allow-unauthenticated alsa-utils'

- name: Default audio settings
  copy:
    dest: '{{ inventory_dir }}/root/var/lib/alsa/asound.state'
    src: asound.state

- name: Restore audio settings on boot
  copy:
    dest: '{{ inventory_dir}}/root/etc/systemd/system/alsa-restore.service'
    src: alsa-restore.service

- name: Enable alsa restore service
  command: 'chroot {{ inventory_dir }}/root systemctl enable alsa-restore'
