---
- name: Fetch JiveLite Debian package
  get_url:
    url: 'https://github.com/robinelfrink/jivelite/releases/download/debian_v0.1.0/jivelite_0.1.0_i386.deb'
    checksum: 'sha256:24b7be95f9e012a70db3fd1cede0ef567eeb49ef5bb96d5baebfa9ff91b42157'
    dest: '{{ inventory_dir }}/root/tmp/'

- name: Install JiveLite
  environment:
    DEBIAN_FRONTEND: noninteractive
  command: 'chroot {{ inventory_dir }}/root apt install --assume-yes --allow-unauthenticated --fix-broken /tmp/jivelite_0.1.0_i386.deb'

- name: Install squeezelite and the libts binaries
  environment:
    DEBIAN_FRONTEND: noninteractive
  command: 'chroot {{ inventory_dir }}/root apt install --assume-yes --allow-unauthenticated squeezelite libts-bin'

- name: Run tslib input wrapper
  copy:
    dest: '{{ inventory_dir }}/root/etc/systemd/system/ts_uinput.service'
    src: ts_uinput.service

- name: Enable tslib input wrapper
  command: 'chroot {{ inventory_dir }}/root systemctl enable ts_uinput'

- name: Set default pointer calibration values
  copy:
    dest: '{{ inventory_dir }}/root/etc/pointercal'
    content: '1593 64 -1303296 6 985 -645765 65536 800 480 0'

- name: Start jivelite automatically
  copy:
    dest: '{{ inventory_dir }}/root/etc/systemd/system/jivelite.service'
    content: |
      [Unit]
      Description=JiveLite
      After=local-fs.target systemd-sysctl.service systemd-modules-load.service

      [Install]
      WantedBy=multi-user.target

      [Service]
      Type=simple
      ExecStart=/usr/bin/jivelite
      Restart=always
      RestartSec=5

- name: Enable jivelite
  command: 'chroot {{ inventory_dir }}/root systemctl enable jivelite'

- name: Create JiveLite settings directory
  file:
    path: '{{ inventory_dir }}/root/home/joggler/.jivelite/userpath/settings'
    state: directory

- name: Set JiveLite skin
  copy:
    dest: '{{ inventory_dir }}/root/home/joggler/'
    src: .jivelite

- name: Set files and directories owner
  command: 'chroot {{ inventory_dir }}/root chown -R joggler:joggler /home/joggler'
