#!/bin/bash

# openframe-mac v2.01 (13th January 2018)
#  Manages MAC addresses on OpenFrame devices.
#  We copy the MAC from the first found wireless interface to
#  the ethernet interface, but with the local bit set.
#  If no wireless interface is available, we generate a MAC for
#  the ethernet interface.

ETH=`ls /sys/class/net/ | grep '^en' | head -1`
ETH_MAC=""
DEVICES=`ls /sys/class/net/ | grep '^wl'`
if [ "${DEVICES}" != "" ]; then
	for DEVICE in $DEVICES; do
		DEVICE_MAC=`cat /sys/class/net/${DEVICE}/address`
		ETH_MAC=`echo ${DEVICE_MAC} | sed 's/^00:/02:/'`
	done
fi
if [ "${ETH_MAC}" = "" ]; then
	ETH_MAC="02:`md5sum /sys/firmware/acpi/tables/DSDT | sed -r "s/(.{2})/\1:/g; s/^(.{14}).*/\1/"`"
fi

ip link set ${ETH} address ${ETH_MAC}

exit 0
